name: ridex
description: "A new Flutter project for Coimbatore Student Bus Pass."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # Icons
  cupertino_icons: ^1.0.8

  # --- FIREBASE (Must be indented like this) ---
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4

  # --- MAPS & LOCATION ---
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0

  # --- UI & TOOLS ---
  http: ^1.3.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/